services:
  db_product:
    image: postgres:15.1-alpine
    volumes:
      - product_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
    ports:
      - 5432:5432

  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /app/
      - ./rsa_public.pem:/app/services/auth/rsa_public.pem:ro
      - ./rsa_private.pem:/app/services/auth/rsa_private.pem:ro
    networks:
      - backend
    ports:
      - '1323:1323'
    restart: unless-stopped

  product-service:
    image: product-service
    build:
      context: .
      dockerfile: ./services/product/Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /app/
      - ./rsa_public.pem:/app/services/product/rsa_public.pem:ro
    depends_on:
      - db_product
    environment:
      - DATABASE_URL=postgres://postgres:secret@db_product:5432/postgres
    networks:
      - backend
    ports:
      - '1324:1324'
    restart: unless-stopped

volumes:
  product_db_data:
networks:
  backend:
