version: '3.8'

services:
  db_product:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: product_db
    ports:
      - '5432:5432'
    volumes:
      - db_product_data:/var/lib/postgresql/data

volumes:
  db_product_data:
