host: localhost:1323
info:
  contact: {}
  description: This is the auth service
  title: Auth Service
  version: "2.0"
paths:
  /authenticate:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      tags:
      - auth
  /logout:
    post:
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      tags:
      - auth
swagger: "2.0"
